### ISSUE TITLE
Document how to enforce a minimum rust version

### ISSUE THREAD

**Issue by spenserblack** [spenserblack/actions-msrv#2]
There should be documentation on how to use this action in a CI that passes if the expected minimum supported Rust version is the *actual* minimum supported Rust version.

For example, something like
```yaml
steps:
  - run: exit 1
    if: ${{ steps.msrv.outputs.msrv == '1.56.0' }} 
```
***NOTE*** The example above isn't the *best* way to fail when the MSRV isn't equal. The example exists to give a general idea of the behavior.
